name: portfolio_opt
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - pandas>=1.5
  - scikit-learn>=1.2
  - matplotlib
  - plotly
  - seaborn
  - jupyterlab
  - notebook
  - pip:
      - yfinance>=0.2.18
      - nsepy>=0.8.0
      - xgboost>=1.7.6
      - lightgbm>=4.0.0
      - cvxpy>=1.3.0
      - PyPortfolioOpt>=1.5.3
      - statsmodels>=0.14.0
      - arch>=5.1.0
      - shap>=0.41.0
      - optuna>=3.2.0
      - mlflow>=2.6.0
      - streamlit>=1.24.0
      - pyyaml
      - python-dotenv
      - tqdm
